### ISSUE TITLE
Library not found for -dlib

### ISSUE THREAD

**Issue by ghost** [RedHandTech/Object_Detector#1]

**Comment by RedHandTech** [comment]
How are you referencing dlib in your project?

**Comment by lendackya** [comment]
I'm also getting this problem. It says: "no such file or directory: '/usr/local/lib/DLIB/iOS/libdlib.a'". Was I suppose to make this file and add to it myself? 

edit: This error appears when I build the project. I also tried to create a folder in lib called DLIB/iOS and put the libdlib.a file in there. The error that appeared then was: 

ld: library not found for -ldlib
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by RedHandTech** [comment]
Yes you need to compile DLIB (see README) and make a folder in your system named at: `/usr/local/lib/DLIB` called `iOS` and put the compiled dlib library there. You can always update the Xcode project to link against a different location if you like.

**Comment by lendackya** [comment]
Okay, I did that, but then I get the error: 

Apple Mach-O Linker (id) Error:

ld: library not found for -ldlib
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by RedHandTech** [comment]
Normally this means that you've not referenced the library correctly. Double check that your `other linker flags` `library search paths` and `header search paths` are correctly configured. I'm afraid I can't help you further without more info.
